name: Deploy Queue Worker

on:
  push:
    branches:
      - main  # or your default branch
    paths:
      - 'src/lib/queue/**'  # Only trigger on queue-related changes
      - 'scripts/**'
      - 'package.json'
      - 'package-lock.json'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            cd ${{ secrets.APP_DIR }}
            git pull
            nvm use 18
            npm i --legacy-peer-deps
            npm run build
            pm2 restart email-queue
            pm2 save