name: Update Changelog

on:
  push:
    branches:
      - main

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Update changelog
        run: |
          # Create public directory if it doesn't exist
          mkdir -p public

          # Function to determine change type from commit message
          get_change_type() {
            local msg="$1"
            if [[ $msg == feat:* || $msg == feature:* ]]; then
              echo "feature"
            elif [[ $msg == improve:* || $msg == enhancement:* ]]; then
              echo "improvement"
            elif [[ $msg == fix:* || $msg == bug:* ]]; then
              echo "fix"
            elif [[ $msg == beta:* ]]; then
              echo "beta"
            elif [[ $msg == chore:* ]]; then
              echo "chore"
            else
              echo "improvement"
            fi
          }

          # Get all commits from 2025
          COMMITS=$(git log --since="2025-01-01" --pretty=format:'{
            "commitHash": "%H",
            "date": "%aI",
            "author": "%an",
            "title": "%s",
            "description": "%b",
            "type": "'$(get_change_type "%s")'"
          },' | sed '$ s/,$//')

          # Create the final JSON structure
          echo "{
            \"lastUpdated\": \"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\",
            \"entries\": [
              $COMMITS
            ]
          }" > public/changelog.json

          # Commit and push the updated changelog
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add public/changelog.json
          git commit -m "chore: Update changelog [skip ci]"
          git push